project_id = "ddfslywzgddlpmkhohfu"

[functions.send-auth-email]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.signup]
verify_jwt = false

[functions.discord-oauth-callback]
verify_jwt = false

[functions.discord-unlink]
verify_jwt = false

[functions.discord-send-dm]
verify_jwt = false

[functions.discord-config]
verify_jwt = false

[functions.discord-notify]
verify_jwt = false

[functions.discord-create-event]
verify_jwt = false

[functions.discord-forum-post]
verify_jwt = false

[functions.discord-delete-thread]
verify_jwt = false

[functions.game-recommendations]
verify_jwt = false
